version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myfirstlambdasam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iy9a2tbyzmkj"
s3_prefix = "myfirstlambdasam"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
